SPECS = [{'id': 'ENEM-2021-MT-11',
  'data': ['Triângulo equilátero',
           'altura h = 8 cm, indicada na figura',
           'usar √3 ≈ 1,7',
           'a barra tem o comprimento do perímetro'],
  'goal': 'Encontrar o comprimento total da barra.',
  'plan': ['Relacionar a altura h com o lado ℓ do equilátero.',
           'Isolar ℓ sem arredondar cedo demais.',
           'Calcular P=3ℓ e só então usar √3≈1,7.'],
  'visual': 'equilateral',
  'visual_note': 'A altura de 8 cm divide o equilátero em dois triângulos 30°–60°–90° e também divide a base '
                 'ao meio.',
  'steps': [('A altura divide a base ao meio', '8^2+(\\ell/2)^2=\\ell^2'),
            ('Desenvolva o quadrado', '64+{\\ell^2\\over4}=\\ell^2'),
            ('Isole o termo com o lado', '64={3\\ell^2\\over4}'),
            ('Resolva para o lado positivo',
             '\\ell^2={256\\over3}\\quad\\Rightarrow\\quad\\ell={16\\over\\sqrt3}'),
            ('Calcule o perímetro sem arredondar', 'P=3\\ell={48\\over\\sqrt3}=16\\sqrt3'),
            ('Só agora use √3≈1,7', 'P\\approx16\\cdot1{,}7=27{,}2\\ \\mathrm{cm}')],
  'answer': 'D',
  'statement_visual': 'triangle_instrument',
  'hook': 'Do desenho para a fórmula: a altura de 8 cm é a chave.'},
 {'id': 'ENEM-2021-MT-12',
  'data': ['topo: diâmetro 10 cm ⇒ R = 5 cm',
           'base: diâmetro 8 cm ⇒ r = 4 cm',
           'altura h = 12 cm',
           'π ≈ 3 e 1 cm³ = 1 mL'],
  'goal': 'Calcular a capacidade da caneca.',
  'plan': ['Reconhecer um tronco de cone.', 'Aplicar a fórmula do volume.', 'Converter cm³ em mL.'],
  'visual': 'cone_frustum',
  'visual_note': 'As duas bases paralelas têm raios diferentes: é um tronco de cone.',
  'steps': [('Volume do tronco de cone', 'V={\\pi h\\over3}(R^2+Rr+r^2)'),
            ('Substitua os dados', 'V={3\\cdot12\\over3}(5^2+5\\cdot4+4^2)'),
            ('Cancele 3 no numerador e denominador', 'V=12(25+20+16)'),
            ('Some dentro dos parênteses', 'V=12\\cdot61=732\\ \\mathrm{cm^3}'),
            ('Use 1 cm³ = 1 mL', 'V=732\\ \\mathrm{mL}')],
  'answer': 'C',
  'statement_visual': 'cup_frustum',
  'hook': 'A caneca não é um cilindro: os dois raios são diferentes.'},
 {'id': 'ENEM-2021-MT-13',
  'data': ['custo: R$ 0,01 por cm²',
           'limite: R$ 0,80 ⇒ área máxima permitida 80 cm²',
           'triângulo ℓ=12; quadrado ℓ=8',
           'retângulo 11×8; hexágono ℓ=6; círculo d=10',
           'π≈3 e √3≈1,7'],
  'goal': 'Escolher a maior área que não ultrapasse 80 cm².',
  'plan': ['Calcular a área dos cinco modelos.',
           'Eliminar os que custam mais de R$ 0,80.',
           'Comparar os modelos restantes.'],
  'visual': 'shape_areas',
  'visual_note': 'O critério tem duas etapas: respeitar o preço e só depois maximizar a área.',
  'steps': [('Triângulo equilátero', 'A_t={\\sqrt3\\over4}12^2={1{,}7\\over4}144=61{,}2'),
            ('Quadrado', 'A_q=8^2=64'),
            ('Retângulo', 'A_r=11\\cdot8=88>80\\quad\\text{elimine}'),
            ('Hexágono: seis equiláteros', 'A_h=6{\\sqrt3\\over4}6^2=91{,}8>80\\quad\\text{elimine}'),
            ('Círculo de raio 5', 'A_c=\\pi5^2=3\\cdot25=75'),
            ('Maior área admissível', '75>64>61{,}2\\quad\\Rightarrow\\quad\\text{círculo}')],
  'answer': 'E',
  'statement_visual': None,
  'hook': 'Primeiro traduza o limite de preço em um limite de área.'},
 {'id': 'ENEM-2021-MT-17',
  'data': ['contêiner retangular',
           'comprimento e largura dobram',
           'altura permanece igual',
           'paredes pintadas nos dois lados; piso apenas internamente'],
  'goal': 'Determinar como mudam as quantidades de tinta.',
  'plan': ['Escrever a área das paredes.', 'Aplicar L→2L e W→2W.', 'Fazer o mesmo com o piso.'],
  'visual': 'box',
  'visual_note': 'A altura não muda: as paredes recebem apenas um fator 2; o piso recebe dois.',
  'steps': [('Área das quatro paredes, em um lado', 'A_p=2Lh+2Wh=2h(L+W)'),
            ('Dobrar L e W', "A'_p=2h(2L+2W)"),
            ('Coloque 2 em evidência', "A'_p=2\\,[2h(L+W)]=2A_p"),
            ('Área do piso', 'A_f=LW'),
            ('Dobrar as duas dimensões do piso', "A'_f=(2L)(2W)=4LW=4A_f"),
            ('Resultado', '\\text{paredes: dobro; piso: quádruplo}')],
  'answer': 'B',
  'statement_visual': None,
  'hook': 'Dobrar comprimentos não multiplica todas as áreas pelo mesmo fator.'},
 {'id': 'ENEM-2021-MT-18',
  'data': ['100 habitantes',
           '120 L por pessoa por dia',
           'autonomia de 7 dias',
           'cilindro com diâmetro 5 m ⇒ r=2,5 m',
           'π≈3'],
  'goal': 'Encontrar a altura mínima do reservatório.',
  'plan': ['Calcular a demanda total.', 'Converter litros em metros cúbicos.', 'Usar V=πr²h e isolar h.'],
  'visual': 'cylinder',
  'visual_note': 'No cilindro, aumentar a altura aumenta o volume linearmente.',
  'steps': [('Demanda em litros', 'V=100\\cdot120\\cdot7=84\\,000\\ \\mathrm L'),
            ('Converta: 1 m³ = 1000 L', 'V=84\\,000/1000=84\\ \\mathrm{m^3}'),
            ('Volume do cilindro', '84=\\pi r^2h=3(2{,}5)^2h'),
            ('Calcule o quadrado do raio', '84=3\\cdot6{,}25h=18{,}75h'),
            ('Divida ambos os lados por 18,75', 'h={84\\over18{,}75}=4{,}48\\ \\mathrm m')],
  'answer': 'D',
  'statement_visual': None,
  'hook': 'Transforme a demanda de água em volume e compare com o cilindro.'},
 {'id': 'ENEM-2021-MT-28',
  'data': ['ponte real: 38,4 m',
           'ponte na réplica: 160 cm',
           'largura real: 1,68 m',
           'largura na réplica: 7 cm'],
  'goal': 'Encontrar a escala da réplica.',
  'plan': ['Colocar real e desenho na mesma unidade.', 'Formar desenho/real.', 'Simplificar a razão.'],
  'visual': 'scale',
  'visual_note': 'Uma escala 1:n significa que uma unidade no desenho representa n unidades reais.',
  'steps': [('Converta 38,4 m para centímetros', '38{,}4\\ \\mathrm m=3840\\ \\mathrm{cm}'),
            ('Razão desenho sobre real', 'E={160\\over3840}'),
            ('Divida numerador e denominador por 160', 'E={1\\over24}=1:24'),
            ('Conferência pela largura', '{7\\over168}={1\\over24}')],
  'answer': 'C',
  'statement_visual': 'castle_scale',
  'hook': 'Escala só funciona depois que as duas medidas estão na mesma unidade.'},
 {'id': 'ENEM-2022-MT-07',
  'data': ['modelo I: área da base A e profundidade P',
           'II: 2P e A/2',
           'III: 2P e raio r/2',
           'IV: P/2 e área 2A',
           'V: P/2 e raio 2r'],
  'goal': 'Identificar a caixa de maior capacidade.',
  'plan': ['Usar V=A_bh.', 'Lembrar que a área varia com r².', 'Comparar todos com AP.'],
  'visual': 'cylinder_compare',
  'visual_note': 'Dobrar o raio quadruplica a área da base; isso é diferente de dobrar a própria área.',
  'steps': [('Modelo I', 'V_I=AP'),
            ('Modelo II', 'V_{II}=(A/2)(2P)=AP'),
            ('Modelo III: metade do raio dá 1/4 da área', 'V_{III}=(A/4)(2P)=AP/2'),
            ('Modelo IV', 'V_{IV}=(2A)(P/2)=AP'),
            ('Modelo V: dobro do raio dá 4A', 'V_V=(4A)(P/2)=2AP'),
            ('Compare', '2AP>AP>AP/2\\quad\\Rightarrow\\quad V')],
  'answer': 'E',
  'statement_visual': None,
  'hook': 'Aqui a armadilha é confundir dobrar o raio com dobrar a área.'},
 {'id': 'ENEM-2022-MT-10',
  'data': ['cidade A em (20,40)',
           'cidade B em (50,20)',
           'a Rodovia 003 coincide com o eixo x',
           'candidatos I–V; o ponto IV está em x=40'],
  'goal': 'Escolher a conexão que minimiza a soma das duas rodovias.',
  'plan': ['Refletir B em relação ao eixo x.',
           'Trocar o caminho A–X–B pelo segmento reto A–B′.',
           'Achar a interseção desse segmento com o eixo x.'],
  'visual': 'reflection',
  'visual_note': 'Como XB=XB′, qualquer caminho A–X–B tem o mesmo comprimento de A–X–B′; a menor soma ocorre '
                 'quando A, X e B′ ficam alinhados.',
  'steps': [('Reflita B=(50,20) no eixo x', "B'=(50,-20)"),
            ('Coeficiente angular de A até B′', 'm={-20-40\\over50-20}=-2'),
            ('Equação da reta passando por A', 'y-40=-2(x-20)'),
            ('No ponto de conexão, y=0', '0-40=-2(x-20)'),
            ('Resolva a equação', '40=2x-40\\quad\\Rightarrow\\quad x=40'),
            ('O candidato em x=40 é IV', 'X=(40,0)\\quad\\Rightarrow\\quad IV')],
  'answer': 'D',
  'statement_visual': 'roads',
  'hook': 'Um truque de reflexão transforma duas distâncias em uma única reta.'},
 {'id': 'ENEM-2022-MT-12',
  'data': ['receita: 50 esferas de diâmetro 2 cm',
           'pedido: 150 esferas de diâmetro 4 cm',
           'o diâmetro e o raio dobram',
           'volume de esfera varia com r³'],
  'goal': 'Calcular quantas receitas de massa são necessárias.',
  'plan': ['Calcular o fator de volume de cada doce.',
           'Calcular o fator da quantidade de doces.',
           'Multiplicar os dois fatores.'],
  'visual': 'sphere_scale',
  'visual_note': 'Dobrar as três dimensões multiplica o volume por 2³=8.',
  'steps': [('Razão dos raios', 'k={4\\over2}=2'),
            ('Fator do volume', "{V'\\over V}=k^3=2^3=8"),
            ('Fator da quantidade', '{150\\over50}=3'),
            ('Massa total necessária', '3\\cdot8=24\\ \\text{receitas}')],
  'answer': 'E',
  'statement_visual': None,
  'hook': 'Dobrar o diâmetro dobra o raio, mas multiplica o volume por oito.'},
 {'id': 'ENEM-2022-MT-13',
  'data': ['cone original: diâmetro 8 cm ⇒ r=4 cm',
           'altura permanece 10 cm',
           'novo volume é 19% menor ⇒ 81% do original'],
  'goal': 'Encontrar o novo raio.',
  'plan': ['Formar a razão entre os volumes.',
           'Cancelar fatores iguais.',
           'Extrair a raiz quadrada positiva.'],
  'visual': 'cone',
  'visual_note': 'Com a altura fixa, o volume do cone é proporcional ao quadrado do raio.',
  'steps': [('Volumes antigo e novo', "V={1\\over3}\\pi(4)^2(10),\\quad V'={1\\over3}\\pi r'^2(10)"),
            ('Use V′=0,81V', "{1\\over3}\\pi r'^2(10)=0{,}81{1\\over3}\\pi(4)^2(10)"),
            ('Cancele π, 10 e 1/3', "r'^2=0{,}81\\cdot16=12{,}96"),
            ('Raiz positiva', "r'=\\sqrt{12{,}96}=3{,}6\\ \\mathrm{cm}")],
  'answer': 'C',
  'statement_visual': 'cone_dims',
  'hook': 'Com a altura fixa, basta acompanhar o quadrado do raio.'},
 {'id': 'ENEM-2022-MT-25',
  'data': ['planta na escala 1:50',
           'espaço: 3,8 cm de altura e 1,6 cm de largura',
           'folga mínima superior: 10 cm',
           'folga lateral: 10 cm de cada lado'],
  'goal': 'Encontrar altura e largura máximas do refrigerador.',
  'plan': ['Converter as dimensões da planta.',
           'Subtrair as folgas corretas.',
           'Converter centímetros em metros.'],
  'visual': 'scale',
  'visual_note': 'A folga é unilateral na altura e bilateral na largura.',
  'steps': [('Altura real do espaço', '3{,}8\\cdot50=190\\ \\mathrm{cm}'),
            ('Largura real do espaço', '1{,}6\\cdot50=80\\ \\mathrm{cm}'),
            ('Retire 10 cm acima', 'H_{ref}=190-10=180\\ \\mathrm{cm}=1{,}80\\ \\mathrm m'),
            ('Retire 10 cm de cada lado', 'L_{ref}=80-2\\cdot10=60\\ \\mathrm{cm}=0{,}60\\ \\mathrm m')],
  'answer': 'A',
  'statement_visual': None,
  'hook': 'Converta a planta e depois retire as folgas: uma em cima e duas nas laterais.'},
 {'id': 'ENEM-2022-MT-32',
  'data': ['piscina retangular sem tampa',
           'volume fixo: 90 000 L = 90 m³',
           'cinco projetos (h, largura, comprimento)',
           'revestir fundo e quatro paredes'],
  'goal': 'Escolher o projeto de menor área interna.',
  'plan': ['Usar A=LW+2h(L+W).', 'Calcular a área dos cinco projetos.', 'Selecionar o menor valor.'],
  'visual': 'pool',
  'visual_note': 'Não há tampa: revestimos o fundo e as quatro paredes.',
  'steps': [('Fórmula da área interna', 'A=LW+2hL+2hW=LW+2h(L+W)'),
            ('Projeto I: (1,8;2;25)', 'A_I=50+3{,}6(27)=147{,}2'),
            ('Projeto II: (2;5;9)', 'A_{II}=45+4(14)=101'),
            ('Projeto III: (1;6;15)', 'A_{III}=90+2(21)=132'),
            ('Projeto IV: (1,5;15;4)', 'A_{IV}=60+3(19)=117'),
            ('Projeto V: (2,5;3;12)', 'A_V=36+5(15)=111'),
            ('Menor área', '101<111<117<132<147{,}2\\quad\\Rightarrow II')],
  'answer': 'B',
  'statement_visual': None,
  'hook': 'O volume é fixo; vence o projeto que gastar menos área de revestimento.'},
 {'id': 'ENEM-2022-MT-34',
  'data': ['cilindro: r=4 cm e h=50 cm', 'esferas: diâmetro 1 cm ⇒ R=0,5 cm', 'sem perda de material'],
  'goal': 'Encontrar quantas esferas podem ser produzidas.',
  'plan': ['Calcular o volume do cilindro.',
           'Calcular o volume de uma esfera.',
           'Dividir o volume total pelo unitário.'],
  'visual': 'cylinder_sphere',
  'visual_note': 'Conservação de volume: o metal apenas muda de forma.',
  'steps': [('Volume do cilindro', 'V_c=\\pi4^2\\cdot50=800\\pi'),
            ('Volume de uma esfera', 'V_e={4\\over3}\\pi(1/2)^3'),
            ('Calcule (1/2)³', 'V_e={4\\over3}\\pi{1\\over8}={\\pi\\over6}'),
            ('Número de esferas', 'n={V_c\\over V_e}={800\\pi\\over\\pi/6}'),
            ('Cancele π e multiplique pelo inverso', 'n=800\\cdot6=4800')],
  'answer': 'D',
  'statement_visual': None,
  'hook': 'Sem perda de material, o volume do cilindro vira a soma dos volumes das esferas.'},
 {'id': 'ENEM-2023-MT-04',
  'data': ['3 pisos de 1,0×0,25 m',
           '3 espelhos de 1,0×0,20 m',
           'cada lateral: retângulos 0,25×0,20; 0,25×0,40; 0,25×0,60',
           'duas paredes laterais'],
  'goal': 'Calcular toda a área revestida.',
  'plan': ['Somar as áreas dos pisos.',
           'Somar as áreas dos espelhos.',
           'Calcular duas laterais e totalizar.'],
  'visual': 'stairs',
  'visual_note': 'Separe a superfície em retângulos sem sobreposição.',
  'steps': [('Três pisos', 'A_p=3(1\\cdot0{,}25)=0{,}75'),
            ('Três espelhos', 'A_e=3(1\\cdot0{,}20)=0{,}60'),
            ('Uma lateral', 'A_l=0{,}25(0{,}20+0{,}40+0{,}60)=0{,}30'),
            ('Duas laterais', '2A_l=2(0{,}30)=0{,}60'),
            ('Área total', 'A=0{,}75+0{,}60+0{,}60=1{,}95\\ \\mathrm{m^2}')],
  'answer': 'E',
  'statement_visual': 'stairs',
  'hook': 'A estratégia é desmontar a escada em retângulos sem contar nenhuma face duas vezes.'},
 {'id': 'ENEM-2023-MT-06',
  'data': ['lua representada por um círculo',
           'telhado é um triângulo equilátero',
           'um vértice do telhado coincide com o centro da lua',
           'a parte escondida é a interseção das figuras'],
  'goal': 'Nomear geometricamente a região escondida.',
  'plan': ['Identificar as fronteiras da região.',
           'Observar que dois lados saem do centro.',
           'Comparar com as definições das alternativas.'],
  'visual': 'sector',
  'visual_note': 'A região é limitada por dois raios e pelo arco entre eles.',
  'steps': [('Dois lados do telhado partem do centro', 'SA=SB=R'),
            ('A terceira fronteira é um arco', '\\widehat{AB}\\subset\\text{circunferência}'),
            ('Definição', '\\text{dois raios + um arco}=\\text{setor circular}')],
  'answer': 'B',
  'statement_visual': 'moon_castle',
  'hook': 'Observe apenas a região escondida: dois raios e um arco.'},
 {'id': 'ENEM-2023-MT-07',
  'data': ['piscina quadrada com área 400 m²',
           'calçada de 5 m ao redor',
           'largura acrescentada nos dois lados de cada dimensão'],
  'goal': 'Encontrar somente a área da calçada.',
  'plan': ['Extrair a raiz para achar o lado da piscina.',
           'Calcular o lado do quadrado externo.',
           'Subtrair a área interna.'],
  'visual': 'pool',
  'visual_note': 'Calçada = quadrado externo menos quadrado interno.',
  'steps': [('Área da piscina', '\\ell^2=400'),
            ('Raiz positiva', '\\ell=\\sqrt{400}=20\\ \\mathrm m'),
            ('Lado externo', 'L=20+5+5=30\\ \\mathrm m'),
            ('Diferença de áreas', 'A_{cal}=30^2-20^2'),
            ('Calcule', 'A_{cal}=900-400=500\\ \\mathrm{m^2}')],
  'answer': 'D',
  'statement_visual': 'pool',
  'hook': 'A calçada é uma moldura: quadrado de fora menos quadrado de dentro.'},
 {'id': 'ENEM-2023-MT-15',
  'data': ['cone maior: R=9 cm e H=36 cm',
           'cone retirado: r=3 cm',
           'cones semelhantes',
           'perfuração cilíndrica de raio 3 cm atravessa o tronco',
           'densidade 0,6 g/cm³; π≈3'],
  'goal': 'Calcular a massa da escultura restante.',
  'plan': ['Achar a altura do cone pequeno por semelhança.',
           'Subtrair os volumes dos cones.',
           'Subtrair o cilindro e aplicar a densidade.'],
  'visual': 'cone_frustum',
  'visual_note': 'Primeiro obtemos o tronco; depois retiramos o furo cilíndrico.',
  'steps': [('Semelhança dos cones', '{h\\over36}={3\\over9}={1\\over3}'),
            ('Altura do cone pequeno', 'h=36/3=12\\ \\mathrm{cm}'),
            ('Volume do cone maior', 'V_M={1\\over3}\\cdot3\\cdot9^2\\cdot36=2916'),
            ('Volume do cone pequeno', 'V_m={1\\over3}\\cdot3\\cdot3^2\\cdot12=108'),
            ('Altura do tronco', 'H_t=36-12=24'),
            ('Volume do cilindro retirado', 'V_c=3\\cdot3^2\\cdot24=648'),
            ('Volume restante', 'V=2916-108-648=2160\\ \\mathrm{cm^3}'),
            ('Massa = densidade × volume', 'm=0{,}6\\cdot2160=1296\\ \\mathrm g')],
  'answer': 'B',
  'statement_visual': 'sculpture',
  'hook': 'A escultura final nasce de duas subtrações de volume, seguidas pela densidade.'},
 {'id': 'ENEM-2023-MT-29',
  'data': ['roda-gigante gira com velocidade angular constante',
           'pessoa começa no ponto mais alto',
           'altura varia continuamente e periodicamente',
           'o ponto mais baixo fica acima do solo'],
  'goal': 'Escolher o gráfico altura × tempo.',
  'plan': ['Modelar o movimento circular uniforme.',
           'Projetar a posição vertical.',
           'Comparar forma, período e valor inicial.'],
  'visual': 'ferris',
  'visual_note': 'A altura é a projeção vertical de um raio que gira uniformemente.',
  'steps': [('Ângulo cresce linearmente', '\\theta(t)=\\omega t'),
            ('Começando no topo', 'h(t)=h_c+R\\cos(\\omega t)'),
            ('No instante inicial', 'h(0)=h_c+R\\quad\\text{máximo}'),
            ('A curva é suave e periódica', 'h(t+2\\pi/\\omega)=h(t)'),
            ('Logo, é uma cossenoide', '\\text{gráfico A}')],
  'answer': 'A',
  'statement_visual': 'ferris_choices',
  'hook': 'Movimento circular uniforme visto na vertical produz uma cossenoide.'},
 {'id': 'ENEM-2023-MT-31',
  'data': ['75 moradores',
           'consumo habitual 200 L/pessoa/dia',
           'água restante: cilindro de r=5 m e h=1,5 m',
           'racionamento por 10 dias',
           'π≈3'],
  'goal': 'Achar a economia mínima diária por morador.',
  'plan': ['Calcular a água restante.',
           'Distribuir por morador e por dia.',
           'Comparar com o consumo habitual.'],
  'visual': 'cylinder',
  'visual_note': 'A coluna de 1,5 m determina diretamente o volume ainda disponível.',
  'steps': [('Volume restante', 'V=\\pi r^2h=3\\cdot5^2\\cdot1{,}5=112{,}5\\ \\mathrm{m^3}'),
            ('Converta em litros', '112{,}5\\ \\mathrm{m^3}=112500\\ \\mathrm L'),
            ('Pessoas-dia', '75\\cdot10=750'),
            ('Consumo diário possível', '{112500\\over750}=150\\ \\mathrm L'),
            ('Economia mínima', '200-150=50\\ \\mathrm{L/pessoa/dia}')],
  'answer': 'A',
  'statement_visual': None,
  'hook': 'Descubra quanto cada morador pode gastar por dia e compare com os 200 litros habituais.'},
 {'id': 'ENEM-2023-MT-33',
  'data': ['cisterna com área da base 3 m²',
           'vazão constante',
           '6h: 0,5 m; 8h: 1,1 m; 12h: 2,3 m; 15h: 3,2 m'],
  'goal': 'Calcular a vazão em m³/h.',
  'plan': ['Escolher dois registros.',
           'Calcular a variação de altura e tempo.',
           'Converter altura em volume pela área da base.'],
  'visual': 'cylinder',
  'visual_note': 'Em base constante, ΔV=A_b·Δh; por isso altura e tempo variam linearmente.',
  'steps': [('De 6h a 8h', '\\Delta t=8-6=2\\ \\mathrm h'),
            ('Variação da altura', '\\Delta h=1{,}1-0{,}5=0{,}6\\ \\mathrm m'),
            ('Variação do volume', '\\Delta V=A_b\\Delta h=3\\cdot0{,}6=1{,}8\\ \\mathrm{m^3}'),
            ('Vazão', 'Q={\\Delta V\\over\\Delta t}={1{,}8\\over2}=0{,}9\\ \\mathrm{m^3/h}'),
            ('Conferência: de 12h a 15h', 'Q={3(3{,}2-2{,}3)\\over15-12}=0{,}9')],
  'answer': 'C',
  'statement_visual': 'cistern_table',
  'hook': 'Vazão constante significa crescimento linear do nível; dois registros já bastam.'},
 {'id': 'ENEM-2023-MT-41',
  'data': ['cabo, mastro e chão formam triângulo retângulo',
           'opção 1: h=11 m, α=30°',
           'opção 2: h=12 m, α=45°',
           'opção 3: h=18 m, α=60°',
           'escolher o menor cabo'],
  'goal': 'Comparar os comprimentos dos três cabos.',
  'plan': ['Identificar h como cateto oposto e cabo como hipotenusa.',
           'Usar sen α=h/c.',
           'Calcular e comparar as três opções.'],
  'visual': 'mast',
  'visual_note': 'O cabo é a hipotenusa; a altura h fica oposta ao ângulo com o chão.',
  'steps': [('Isole o cabo c', '\\sin\\alpha={h\\over c}\\quad\\Rightarrow\\quad c={h\\over\\sin\\alpha}'),
            ('Opção 1', 'c_1={11\\over\\sin30^\\circ}={11\\over1/2}=22'),
            ('Opção 2', 'c_2={12\\over\\sin45^\\circ}={12\\over\\sqrt2/2}'),
            ('Racionalize ou multiplique pelo inverso', 'c_2={24\\over\\sqrt2}={24\\sqrt2\\over2}=12\\sqrt2'),
            ('Opção 3', 'c_3={18\\over\\sin60^\\circ}={18\\over\\sqrt3/2}=12\\sqrt3'),
            ('Compare aproximações', '12\\sqrt2\\approx16{,}97<12\\sqrt3\\approx20{,}78<22')],
  'answer': 'C',
  'statement_visual': 'mast',
  'hook': 'O cabo é a hipotenusa; o seno liga diretamente altura, ângulo e comprimento.'},
 {'id': 'ENEM-2023-MT-42',
  'data': ['malha: quadrados de 1 cm',
           'maior altitude na tela: 1 cm',
           'maior altitude real: 5 km',
           'escala deve usar a mesma unidade'],
  'goal': 'Determinar a escala da tela.',
  'plan': ['Ler a maior ordenada no gráfico.',
           'Converter 5 km para centímetros.',
           'Formar a razão tela/real.'],
  'visual': 'graph_scale',
  'visual_note': 'O maior patamar do gráfico tem uma unidade vertical, isto é, 1 cm na tela.',
  'steps': [('Converta quilômetros em metros', '5\\ \\mathrm{km}=5000\\ \\mathrm m'),
            ('Converta metros em centímetros', '5000\\ \\mathrm m=500000\\ \\mathrm{cm}'),
            ('Escala', 'E={1\\ \\mathrm{cm}\\over500000\\ \\mathrm{cm}}'),
            ('Forma 1:n', 'E=1:500000')],
  'answer': 'E',
  'statement_visual': 'graph_scale',
  'hook': 'Leia um centímetro na tela, converta a altitude real e forme a escala.'},
 {'id': 'ENEM-2023-MT-44',
  'data': ['lado a está oposto ao ângulo α',
           'diâmetros das pizzas são a, b e c',
           'área de círculo é proporcional ao quadrado do diâmetro',
           'área da pizza do professor é maior que a soma das outras'],
  'goal': 'Determinar em que intervalo está α.',
  'plan': ['Transformar a comparação de áreas em comparação de quadrados.',
           'Aplicar a lei dos cossenos.',
           'Analisar o sinal de cos α.'],
  'visual': 'pizza',
  'visual_note': 'Como A=π(d/2)², o fator π/4 é igual para todas as pizzas e pode ser cancelado.',
  'steps': [('Condição de áreas', '{\\pi\\over4}a^2>{\\pi\\over4}b^2+{\\pi\\over4}c^2'),
            ('Cancele o fator positivo π/4', 'a^2>b^2+c^2'),
            ('Lei dos cossenos', 'a^2=b^2+c^2-2bc\\cos\\alpha'),
            ('Substitua na desigualdade', 'b^2+c^2-2bc\\cos\\alpha>b^2+c^2'),
            ('Subtraia b²+c² dos dois lados', '-2bc\\cos\\alpha>0'),
            ('Como b,c>0, divida por −2bc e inverta o sinal', '\\cos\\alpha<0'),
            ('Cosseno negativo no triângulo', '90^\\circ<\\alpha<180^\\circ')],
  'answer': 'C',
  'statement_visual': 'pizza_pythagoras',
  'hook': 'Áreas de pizzas viram quadrados dos diâmetros; depois entra a lei dos cossenos.'},
 {'id': 'ENEM-2024-MT-02',
  'data': ['área é um setor circular',
           'cinco pares (α,R)',
           'área mínima exigida: 70 m²',
           'π≈3',
           'menor área admissível corresponde ao menor preço'],
  'goal': 'Escolher o sensor mais barato que cubra pelo menos 70 m².',
  'plan': ['Calcular A=απR²/360 para cada tipo.',
           'Eliminar áreas menores que 70.',
           'Escolher a menor das áreas restantes.'],
  'visual': 'sector',
  'visual_note': 'O setor ocupa a fração α/360° do círculo inteiro.',
  'steps': [('Tipo 1: 15°, R=20', 'A_1={15\\over360}3(20)^2=50'),
            ('Tipo 2: 30°, R=22', 'A_2={30\\over360}3(22)^2=121'),
            ('Tipo 3: 40°, R=12', 'A_3={40\\over360}3(12)^2=48'),
            ('Tipo 4: 60°, R=16', 'A_4={60\\over360}3(16)^2=128'),
            ('Tipo 5: 90°, R=10', 'A_5={90\\over360}3(10)^2=75'),
            ('Admissíveis: 2, 4 e 5; escolha a menor área',
             '75<121<128\\quad\\Rightarrow\\quad\\text{tipo 5}')],
  'answer': 'E',
  'statement_visual': 'sector',
  'hook': 'Não basta cobrir 70 m²: entre os que cobrem, escolha a menor área e portanto o menor preço.'},
 {'id': 'ENEM-2024-MT-05',
  'data': ['área real: 1672 m²', 'escala linear: 1:200', 'pedem área na maquete em cm²'],
  'goal': 'Calcular a área reduzida da maquete.',
  'plan': ['Elevar o fator linear ao quadrado.', 'Aplicar à área real.', 'Converter m² para cm².'],
  'visual': 'scale',
  'visual_note': 'Uma área recebe o fator de escala duas vezes: 1/200².',
  'steps': [('Fator de área', 'k_A=\\left({1\\over200}\\right)^2={1\\over40000}'),
            ('Área na maquete em m²', 'A_m={1672\\over40000}\\ \\mathrm{m^2}'),
            ('Como 1 m² = 10 000 cm²', 'A_m={1672\\over40000}\\cdot10000\\ \\mathrm{cm^2}'),
            ('Cancele 10 000/40 000', 'A_m={1672\\over4}=418\\ \\mathrm{cm^2}')],
  'answer': 'E',
  'statement_visual': None,
  'hook': 'Escala de comprimento vira escala de área ao quadrado.'},
 {'id': 'ENEM-2024-MT-11',
  'data': ['cilindro: r=3 cm e h=15 cm',
           'π≈3',
           'cubo terá 80% da capacidade do cilindro',
           'volume do cubo: a³'],
  'goal': 'Encontrar a aresta do cubo.',
  'plan': ['Calcular o volume cilíndrico.', 'Tomar 80% desse volume.', 'Isolar a por raiz cúbica.'],
  'visual': 'cylinder_compare',
  'visual_note': 'Capacidades iguais significam comparar volumes, não áreas externas.',
  'steps': [('Volume do cilindro', 'V_c=\\pi r^2h=3\\cdot3^2\\cdot15=405'),
            ('O cubo terá 80%', 'V_q=0{,}8\\cdot405=324'),
            ('Volume do cubo', 'a^3=324'),
            ('Extraia a raiz cúbica positiva', 'a=\\sqrt[3]{324}'),
            ('Fatore 324=27·12', 'a=\\sqrt[3]{27\\cdot12}=3\\sqrt[3]{12}\\ \\mathrm{cm}')],
  'answer': 'E',
  'statement_visual': None,
  'hook': 'Primeiro obtenha 80% do volume cilíndrico; depois tire a raiz cúbica.'},
 {'id': 'ENEM-2024-MT-14',
  'data': ['trapézio retângulo PQRS',
           'PQ e RS são paralelos e têm comprimentos diferentes',
           'PS é o eixo de rotação',
           'giro completo de 360°'],
  'goal': 'Identificar o sólido de revolução.',
  'plan': ['Observar as distâncias de PQ e RS ao eixo.',
           'Girar as duas bases em torno de PS.',
           'Identificar a superfície lateral inclinada.'],
  'visual': 'trapezoid_spin',
  'visual_note': 'Os lados paralelos geram círculos de raios diferentes; o lado inclinado gera a lateral.',
  'steps': [('PQ gira e gera uma base circular', 'PQ\\longrightarrow\\text{círculo de raio }R'),
            ('RS gera a outra base', 'RS\\longrightarrow\\text{círculo de raio }r'),
            ('Como R≠r, não é cilindro', 'R\\ne r'),
            ('Duas bases circulares paralelas e lateral inclinada', '\\text{tronco de cone}')],
  'answer': 'D',
  'statement_visual': 'trapezoid_spin',
  'hook': 'Gire mentalmente o trapézio: duas distâncias diferentes ao eixo viram dois raios diferentes.'},
 {'id': 'ENEM-2024-MT-30',
  'data': ['folha lateral: 10×20 cm',
           'embalagem 1: h=20 e circunferência=10',
           'embalagem 2: h=10 e circunferência=20',
           '2πr é a largura enrolada'],
  'goal': 'Escolher a embalagem de maior volume.',
  'plan': ['Achar o raio de cada embalagem.', 'Calcular V=πr²h.', 'Comparar os volumes.'],
  'visual': 'cylinders_sheet',
  'visual_note': 'Ao enrolar a folha, uma dimensão vira altura e a outra vira a circunferência.',
  'steps': [('Embalagem 1: 2πr₁=10', 'r_1={10\\over2\\pi}={5\\over\\pi}'),
            ('Volume 1', 'V_1=\\pi(5/\\pi)^2(20)={500\\over\\pi}'),
            ('Embalagem 2: 2πr₂=20', 'r_2={20\\over2\\pi}={10\\over\\pi}'),
            ('Volume 2', 'V_2=\\pi(10/\\pi)^2(10)={1000\\over\\pi}'),
            ('Compare; π é positivo', '{1000\\over\\pi}>{500\\over\\pi}\\quad\\Rightarrow\\quad V_2')],
  'answer': 'D',
  'statement_visual': 'cylinders_sheet',
  'hook': 'A mesma folha gera dois cilindros; trocar altura e circunferência muda muito o raio.'},
 {'id': 'ENEM-2024-MT-34',
  'data': ['perímetro disponível: k',
           'formas: equilátero, quadrado ou hexágono regular',
           'cada forma deve usar todo o perímetro'],
  'goal': 'Escolher a forma de maior área.',
  'plan': ['Escrever o lado de cada figura em função de k.',
           'Calcular as três áreas.',
           'Comparar os coeficientes de k².'],
  'visual': 'regular_polygons',
  'visual_note': 'Com o mesmo perímetro, aumentar o número de lados aproxima a figura do círculo.',
  'steps': [('Equilátero: lado k/3', 'A_3={\\sqrt3\\over4}(k/3)^2={\\sqrt3\\over36}k^2'),
            ('Quadrado: lado k/4', 'A_4=(k/4)^2={1\\over16}k^2'),
            ('Hexágono: seis equiláteros de lado k/6', 'A_6=6{\\sqrt3\\over4}(k/6)^2={\\sqrt3\\over24}k^2'),
            ('Compare aproximadamente',
             '{\\sqrt3\\over36}\\approx0{,}0481;\\quad{1\\over16}=0{,}0625;\\quad{\\sqrt3\\over24}\\approx0{,}0722'),
            ('Maior coeficiente', 'A_6>A_4>A_3\\quad\\Rightarrow\\quad\\text{hexágono}')],
  'answer': 'A',
  'statement_visual': None,
  'hook': 'Com perímetro fixo, compare as áreas depois de escrever cada lado em função de k.'},
 {'id': 'ENEM-2025-MT-08',
  'data': ['lagoa circular de raio 1 km',
           'π≈3',
           'cada policial protege até 200 m para cada lado',
           'cada policial cobre um arco total de 400 m'],
  'goal': 'Encontrar o número mínimo de policiais.',
  'plan': ['Calcular o comprimento da ciclovia.',
           'Dividir pelo trecho coberto por um policial.',
           'Verificar se é necessário arredondar para cima.'],
  'visual': 'circle_patrol',
  'visual_note': 'Os arcos protegidos devem cobrir toda a circunferência, sem lacunas.',
  'steps': [('Comprimento da ciclovia', 'C=2\\pi r=2\\cdot3\\cdot1=6\\ \\mathrm{km}'),
            ('Converta em metros', '6\\ \\mathrm{km}=6000\\ \\mathrm m'),
            ('Cobertura por policial', '200+200=400\\ \\mathrm m'),
            ('Quantidade', 'n={6000\\over400}=15'),
            ('A divisão é exata; não há resto', '15\\cdot400=6000')],
  'answer': 'C',
  'statement_visual': 'circle_patrol',
  'hook': 'Cada policial cobre um arco de 400 m; falta descobrir quantos desses arcos fecham a '
          'circunferência.'}]
